spring:
  application:
    name: EmailAPI;
  mail:
    host: smtp.gmail.com
    port: 587
    username: isaias.revature@gmail.com
    password: kedyzbimnytvktnz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    smtp:
      debug: true

server:
  port: 8081



